import Head from "next/head";
import HomePage from "../../layouts/home/home";

export default function Shop() {
  return (
    <div>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin={""}
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500;700&display=swap"
          rel="stylesheet"
        />
        <title>shoppingify &mdash; Your all-in-one shop list app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/favicon.png"} />
      </Head>
      <HomePage />
    </div>
  );
}
