import type {NextPage} from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>shoppingify &mdash; Your all-in-one shop list app</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href={"/favicon.png"} />
            </Head>
        </div>
    )
}

export default Home
